### ISSUE TITLE
Download all 5grams at once

### ISSUE THREAD

**Issue by MarjanDavoodi** [dimazest/google-ngram-downloader#21]
Hi,

I'm trying to download all the 2012 English 5grams at once but the problem is that when I include the indices option in my code it seems to be nothing. I still get the URL to download only the 5grams that start with 0. Do you have any idea how this problem can be addressed? Thanks a lot!

**Comment by dimazest** [comment]
How do you provide the indices?

**Comment by MarjanDavoodi** [comment]
That's the line I've been using to get the 5grams starting with 0-9:

fname, url, records = next(readline_google_store(ngram_len=5,indices= ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']))
                                         
fname
url
next(records)

**Comment by dimazest** [comment]
If you want to download **all** 5 grams, you don't need to provide indices.

You can run this command in terminal (this is a good idea if you want to process 5grams several times)
```
google-ngram-downloader download
```
Alternatively, you can iterate over all 5 grams like this
```python
>>> from google_ngram_downloader import readline_google_store
>>>
>>> for fname, url, records in readline_google_store(ngram_len=5):
...     for record in records:
...         """Your processing."""
```
