### ISSUE TITLE
`match_count` vs `volume_count`

### ISSUE THREAD

**Issue by danyaljj** [dimazest/google-ngram-downloader#25]
Anyone knows what is the difference between `volume_count` and `match_count`values? 

```
Record(ngram='0.8665', year=2008, match_count=41, volume_count=34)
```

**Comment by dimazest** [comment]
From the [website](http://storage.googleapis.com/books/ngrams/books/datasetsv2.html):

> File format: Each of the files below is compressed tab-separated data. In Version 2 each line has the following format:
> 
>     ngram TAB year TAB match_count TAB volume_count NEWLINE
> 
> As an example, here are the 3,000,000th and 3,000,001st lines from the a file of the English 1-grams (googlebooks-eng-all-1gram-20120701-a.gz):
> 
>     circumvallate   1978   335    91
>     circumvallate   1979   261    91
> 
> The first line tells us that in 1978, the word "circumvallate" (which means "surround with a rampart or other fortification", in case you were wondering) occurred 335 times overall, in 91 distinct books of our sample. 

`match_count` is the number of time the ngram appeared and `volume_count` is in how many book it appeared.

**Comment by danyaljj** [comment]
Thanks!
